[package]
name = "kaleidoscope_parser"
version = "0.1.0"
authors = ["Jakob Leifhelm <jakob.leifhelm@gmail.com>"]
edition = "2018"

[dependencies]
kaleidoscope_ast = { path = "../kaleidoscope_ast" }
kaleidoscope_error = { path = "../kaleidoscope_error" }
nom = "^7.0"
nom-unicode = "^0.3"