[package]
name = "kaleidoscope_parser"
version = "0.1.0"
authors = ["Jakob Leifhelm <jakob.leifhelm@gmail.com>"]
edition = "2018"

[dependencies]
kaleidoscope_ast = { path = "../kaleidoscope_ast" }
nom = "^6.1"
nom-unicode = "^0.2"